version: '2'
services:

  web:
    image: claydonkey/sloppy-slick:latest
    # volumes:
      #- /home/docker/openshift/slicktest/target/docker/stage/opt:/opt
    links:
      - db:mysql
    ports:
      - 80:9000

  db:
    image: claydonkey/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  all:
