version: '2'
services:
  web:
    image: claydonkey/sloppy-slick:1.0-SNAPSHOT
    #image: claydonkey/sloppy-slick:local
    # volumes:
    #- /home/docker/openshift/slicktest/target/docker/stage/opt:/opt
    environment:
      SLICK_DB: jdbc:mysql://192.168.99.100:3306/slicktest
      SLICK_DB_USER: root  
      SLICK_DB_PASSWORD: example
    links:
      - db:mysql
    ports:
      - 80:9000

  db:
    image: claydonkey/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: slicktest   

networks:
  all:
